### ISSUE TITLE
Can't seem to properly clone library

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [google/mathfu#10]
The instructions regarding the recursive cloning fails on fetching on `fplutil`: "Connection reset by peer".
What is my mistake on this? Tried on Ubuntu Linux 14.04 and OSX Yosemite.
(BTW, I'm able to clone `fplutil`'s HEAD)

**Comment by TheFakeMontyOnTheRun** [comment]
(BTW, I'm able to clone `fplutil`'s HEAD).

**Comment by jsanmiya** [comment]
Hey Daniel,

Sorry you're having this problem.

I just tried it on OSX Yosemite 10.10.5 and got the output below. It
appears to work for me.

It sounds like a networking error. Could you try from a different network,
perhaps?

-----

mathfu jsanmiya$ git clone --recursive https://github.com/google/mathfu.git

Cloning into 'mathfu'...

remote: Counting objects: 2952, done.

remote: Total 2952 (delta 0), reused 0 (delta 0), pack-reused 2952

Receiving objects: 100% (2952/2952), 1.56 MiB | 908.00 KiB/s, done.

Resolving deltas: 100% (1614/1614), done.

Checking connectivity... done.

Submodule 'dependencies/fplutil' (http://github.com/google/fplutil.git)
registered for path 'dependencies/fplutil'

Submodule 'dependencies/googletest' (http://github.com/google/fplutil.git)
registered for path 'dependencies/googletest'

Submodule 'dependencies/vectorial' (http://github.com/scoopr/vectorial.git)
registered for path 'dependencies/vectorial'

Cloning into 'dependencies/fplutil'...

remote: Counting objects: 6029, done.

remote: Total 6029 (delta 0), reused 0 (delta 0), pack-reused 6029

Receiving objects: 100% (6029/6029), 11.15 MiB | 454.00 KiB/s, done.

Resolving deltas: 100% (4145/4145), done.

Checking connectivity... done.

Submodule path 'dependencies/fplutil': checked out
'4a7b677fec6a8c7992a0969f39956efe786f24ab'

Cloning into 'dependencies/googletest'...

remote: Counting objects: 6029, done.

remote: Total 6029 (delta 0), reused 0 (delta 0), pack-reused 6029

Receiving objects: 100% (6029/6029), 11.15 MiB | 855.00 KiB/s, done.

Resolving deltas: 100% (4145/4145), done.

Checking connectivity... done.

Submodule path 'dependencies/googletest': checked out
'67937031e12df3c9821506ec5980584da050658d'

Cloning into 'dependencies/vectorial'...

remote: Counting objects: 1114, done.

remote: Total 1114 (delta 0), reused 0 (delta 0), pack-reused 1114

Receiving objects: 100% (1114/1114), 231.21 KiB | 0 bytes/s, done.

Resolving deltas: 100% (618/618), done.

Checking connectivity... done.

Submodule path 'dependencies/vectorial': checked out
'f3d31522f688ed0c12c7401a4418ef01c2c7c4dd'

**Comment by TheFakeMontyOnTheRun** [comment]
That's really strange. Here is what I got:
```
Daniels-Mac-mini:gitcenter monty$ git clone --recursive https://github.com/google/mathfu.git
Cloning into 'mathfu'...
fatal: unable to access 'https://github.com/google/mathfu.git/': Could not resolve host: github.com
Daniels-Mac-mini:gitcenter monty$ git clone --recursive https://github.com/google/mathfu.git
Cloning into 'mathfu'...
remote: Counting objects: 2952, done.
remote: Total 2952 (delta 0), reused 0 (delta 0), pack-reused 2952
Receiving objects: 100% (2952/2952), 1.56 MiB | 140.00 KiB/s, done.
Resolving deltas: 100% (1614/1614), done.
Checking connectivity... done.
Submodule 'dependencies/fplutil' (http://github.com/google/fplutil.git) registered for path 'dependencies/fplutil'
Submodule 'dependencies/googletest' (http://github.com/google/fplutil.git) registered for path 'dependencies/googletest'
Submodule 'dependencies/vectorial' (http://github.com/scoopr/vectorial.git) registered for path 'dependencies/vectorial'
Cloning into 'dependencies/fplutil'...
fatal: unable to access 'http://github.com/google/fplutil.git/': Recv failure: Connection reset by peer
Clone of 'http://github.com/google/fplutil.git' into submodule path 'dependencies/fplutil' failed
```

**Comment by TheFakeMontyOnTheRun** [comment]
Strangely, just tried on a Linux machine and it worked. Go figure out.
Closing now.
