### ISSUE TITLE
Vector<float, 4> does not have member-wise division operator.

### ISSUE THREAD

**Issue by VladSerhiienko** [google/mathfu#13]
This should be added to the vector_4.h:
  ```
inline Vector<float, 4> operator/(const Vector<float, 4>& v) const {
      return Vector<float, 4>(simd4f_div(data_.simd, v.data_.simd));
  }
```

**Comment by stewartmiles** [comment]
This was fixed a while ago in https://github.com/google/mathfu/commit/6b4159fbf2159e598eb27a1ee8834af7c7f50fb7

**Comment by stewartmiles** [comment]
Oh wait, nope you're right we're still missing that operator.

**Comment by stewartmiles** [comment]
Ok I have a fix pending
