### ISSUE TITLE
Api description in GLSL Mappings for typedef Matrix< float, 4, 4 >

### ISSUE THREAD

**Issue by markus2610** [google/mathfu#35]
The description says 3x3 float Matrix, but 4x4 float Matrix is ​​correct here.

[GLSL Mappings](http://google.github.io/mathfu/group__mathfu__glsl.html#gaa2dcb6916452d11aab6ddc8f02093752)

**Comment by haroonq** [comment]
Fixed in 2852f6556e8979fd5adc5ec3f26decc8c4e3a06a.
