### ISSUE TITLE
Google_MathFu failed to build due to error C1083 with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [google/mathfu#37]
Environment:
Windows Server 2016 + VS2017 + Google_MathFu master branch latest srouce code.

Google_MathFu failed to build due to error C1083:  Cannot open include file: 'third_party/mathfu/include/mathfu/constants.h': No such file or directory with MSVC on windows. It can be first reproduced on master revision d66be09. Could you help have a look about this issue? Thanks in advance!

[log_x86_build.log](https://github.com/google/mathfu/files/3176736/log_x86_build.log)

1.git clone --recursive https://github.com/google/mathfu.git D:\Google-MathFu\src
2.Open a VS 2017 command prompt and browse to D:\Google-MathFu
3.mkdir build_x86 && pushd build_x86
4.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
5.msbuild /p:Configuration=Release;Platform=Win32 build_x86\mathfu.sln /t:Rebuild

Actual result:
D:\Google-Mathfu\src\unit_tests\quaternion_test\quaternion_test.cpp(25,10): error C1083:  Cannot open include file: 'third_party/mathfu/include/mathfu/constants.h': No such file or directory (d:\agent\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1722) [D:\Google-Mathfu\build_x86\unit_tests\quaternion_no_simd_tests.vcxproj]
D:\Google-Mathfu\src\unit_tests\quaternion_test\quaternion_test.cpp(25,10): error C1083: #include "third_party/mathfu/include/mathfu/constants.h" [D:\Google-Mathfu\build_x86\unit_tests\quaternion_no_simd_tests.vcxproj]
D:\Google-Mathfu\src\unit_tests\quaternion_test\quaternion_test.cpp(25,10): error C1083:          ^ [D:\Google-Mathfu\build_x86\unit_tests\quaternion_no_simd_tests.vcxproj]
Done Building Project "D:\Google-Mathfu\build_x86\unit_tests\quaternion_no_simd_tests.vcxproj" (Rebuild target(s)) -- FAILED.
Done Building Project "D:\Google-Mathfu\build_x86\unit_tests\quaternion_no_simd_tests.vcxproj.metaproj" (Rebuild target(s)) -- FAILED.

**Comment by haroonq** [comment]
Should be fixed in a120edf12546afb5d43051daa8739c264975caee.
