### ISSUE TITLE
Difference in perspective matrix between GLM & MathFu

### ISSUE THREAD

**Issue by roxlu** [google/mathfu#6]
When I create a perspective matrix with MathFu like `perspective(45.0f, 1280.0f / 720.0f, 0.1f, 100.0f)`
I get:

````
 1.01,  0.00,  0.00,  0.00
 0.00,  1.79,  0.00,  0.00
 0.00,  0.00, -1.00, -0.10
 0.00,  0.00, -1.00,  0.00
````

Using GLM, I get: 
````
 1.01,  0.00,  0.00,  0.00
 0.00,  1.79,  0.00,  0.00
 0.00,  0.00, -1.00, -0.20
 0.00,  0.00, -1.00,  0.00
````

Wondering why there is a difference?

**Comment by gwvo** [comment]
Yes that's wrong.. will fix.

**Comment by gwvo** [comment]
Fixed in https://github.com/google/mathfu/commit/4903ef1ea76e0d92dcb5df3af4c41bc207a182b1
