### ISSUE TITLE
1.0f / vec2(2.0f, 2.0f) == vec2(2.0f, 2.0f)

### ISSUE THREAD

**Issue by batesj** [google/mathfu#8]
Seems to be a bug in the scalar / vector divide code. I expected a component-wise divide (scalar / v[0], scalar / v[1], ...), matching other vectormath APIs.

**Comment by gwvo** [comment]
That's most definitely a bug, yes. Are you able to make a pull request?

**Comment by TheFakeMontyOnTheRun** [comment]
Had look at the issue, but could not find where the operator overload is declared. I was expecting something along the lines of:
`inline Vector<float, 2>& operator/=(const float &s, const Vector<float, 2>& v)`
Am I missing something?

**Comment by stewartmiles** [comment]
https://github.com/google/mathfu/blob/master/include/mathfu/vector.h#L417
https://github.com/google/mathfu/blob/master/include/mathfu/vector_2.h#L102
https://github.com/google/mathfu/blob/master/include/mathfu/vector_2.h#L118
https://github.com/google/mathfu/blob/master/include/mathfu/vector_2.h#L155

etc.

We have various overloads for each specialized vector e.g vec2, vec3, vec4
etc.

**Comment by TheFakeMontyOnTheRun** [comment]
Precisely. By `grep`ping thru the code, all I could find was overloads dealing with Vec2/Vec2 and Vec2/scalar, but not for scalar/Vec2 (which, in effect, would be scalar * Vec2^(-1) ).

Still, by far, the last few days of digging have been quite fascinating.

**Comment by stewartmiles** [comment]
That will teach me to not read your original message.

Is it possible that you're ending up in
https://github.com/google/mathfu/blob/master/include/mathfu/vector.h#L670
?  It looks like that code is wrong since it should only accept a scalar on
the right-hand side of the expression.  i.e scalar / vector = undefined
<https://en.wikibooks.org/wiki/Fundamentals_of_Physics/Vectors>, vector /
scalar =  piecewise division of each element in the vector.

What code have you written that is problematic, any chance you could share
a snippet?

**Comment by TheFakeMontyOnTheRun** [comment]
Not really mine. I'm just trying to learn from it.
I was unsure of what 1.0/vec2 would mean until I threw it at Wolfram Alpha ( {2.0, 3.0}^-1 got me {1.0/2.0, 1.0/3.0}). Me and my friends were baffled by his outcome.

By doing this on the generic vector wouldn't it be too expensive to go component-by-component? Maybe this couldn't be more efficiently (at the cost of some repetition) dealt at the more specific vectors? Or maybe it would result in unwanted duplicity of effort?

Or even, does it make sense to have it as a general proposition?

**Comment by stewartmiles** [comment]
I would really prefer to not have MathFu include operators that aren't well
defined.

We have specialized implementations of scalar divide for each vector type
which use SIMD when it's available.  As I mentioned scalar / vector sounds
broken.

**Comment by TheFakeMontyOnTheRun** [comment]
I agree. Makes a lot more sense

Maybe @batesj can provide us with more details on his use? Maybe we can suggest alternatives? IDK

**Comment by batesj** [comment]
I would have been happy if my code didn't compile, so feel free to delete the scaler / vector operator.

What I expected was component-wise divide either through implicit construction or directly:
1.0 / vec2 == vec2(1.0) / vec2 == vec2(1.0, 1.0) / vec2

**Comment by stewartmiles** [comment]
https://github.com/google/mathfu/commit/6cb4a104dffe650a1aef67f4b476c9e12f7175c3
