### ISSUE TITLE
Feature req: add method to extract 3x3 rotation matrix from 4x4 homogeneous matrix

### ISSUE THREAD

**Issue by batesj** [google/mathfu#9]
Feature req: add method to extract 3x3 rotation matrix from 4x4 homogeneous matrix.

There's already a way to construct a 4x4 from a 3x3.

**Comment by panzergame** [comment]
Sorry if I'm totally wrong, but Matrix::RotationMatrix isn't doing what you want ?

**Comment by batesj** [comment]
Looks like this was fixed by https://github.com/google/mathfu/commit/077f0ebfcc5c2133b05a0fa341e9b3ef667832e1
